### ISSUE TITLE
Closes tag when `>` is seen inside of an attribute value

### ISSUE THREAD

**Issue by dnd** [alvan/vim-closetag#39] opened 2018-07-21 03:59 UTC
I'm currently building an app with Vue, where the templating will at times have `>` comparisons inside of an attribute value. When that character is entered, closetag immediately closes the tag, even though it shouldn't.

Typing `<div :complete="1 >` will immediately result in `<div :complete="1></div>`. When using the auto-pairs plugin to insert a closing quote as soon as the opening is typed closetag ends up with `<div :complete="1 >"` being converted to `<div :complete="1 ></div>"`.

Is there any kind of setting/flag I need to set, or is this a bug?

**Comment by alvan** [comment] 2018-07-22 09:37
@dnd 
I can't reproduce this issue.
Please check if you are using other plugins for auto closing tags.

**Comment by redbmk** [comment] 2018-07-31 20:50
This happens in `jsx`:

For example trying to write this: `<Checkbox checked={numItems > 0}>Has Items</Checkbox>`

You will get `<Checkbox checked={numItems > </Checkbox>`

**Comment by alvan** [comment] 2018-08-01 10:18
This plugin is mainly used in HTML tags. I don't intend to add support for other syntaxes, because that is basically impossible. Automatically completing tags for specific syntax is a complicated task for such a plugin.

**Comment by alvan** [comment] 2018-08-01 10:20
Please use `<leader>>` to insert ">" directly in this case.

**Closed as completed by alvan** 2018-08-01 10:20 UTC
